#!/bin/bash
#
# Control Tower Setup Wizard
# Guides you through setting up your AI executive team
#

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color
BOLD='\033[1m'

echo ""
echo -e "${CYAN}╔═══════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║${NC}  ${BOLD}🗼 Control Tower Setup Wizard${NC}                             ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}     Your AI Executive Team                                 ${CYAN}║${NC}"
echo -e "${CYAN}╚═══════════════════════════════════════════════════════════╝${NC}"
echo ""

# Pre-flight checks
echo -e "${BLUE}Running pre-flight checks...${NC}"
echo ""

errors=0

# Check Docker
if command -v docker &> /dev/null; then
    docker_version=$(docker --version | cut -d' ' -f3 | tr -d ',')
    echo -e "  ${GREEN}✓${NC} Docker ${docker_version}"
else
    echo -e "  ${RED}✗${NC} Docker not found"
    echo -e "    ${YELLOW}Install Docker: https://docs.docker.com/get-docker/${NC}"
    errors=$((errors + 1))
fi

# Check Docker Compose
if docker compose version &> /dev/null 2>&1; then
    compose_version=$(docker compose version --short 2>/dev/null || echo "v2+")
    echo -e "  ${GREEN}✓${NC} Docker Compose ${compose_version}"
elif command -v docker-compose &> /dev/null; then
    compose_version=$(docker-compose --version | cut -d' ' -f4 | tr -d ',')
    echo -e "  ${GREEN}✓${NC} Docker Compose ${compose_version}"
else
    echo -e "  ${RED}✗${NC} Docker Compose not found"
    errors=$((errors + 1))
fi

# Check Docker running
if docker info &> /dev/null 2>&1; then
    echo -e "  ${GREEN}✓${NC} Docker daemon running"
else
    echo -e "  ${RED}✗${NC} Docker daemon not running"
    echo -e "    ${YELLOW}Start Docker and try again${NC}"
    errors=$((errors + 1))
fi

echo ""

if [ $errors -gt 0 ]; then
    echo -e "${RED}Pre-flight checks failed. Please fix the issues above and try again.${NC}"
    exit 1
fi

echo -e "${GREEN}Pre-flight checks passed!${NC}"
echo ""

# Check if .env already exists
if [ -f .env ]; then
    echo -e "${YELLOW}Found existing .env file.${NC}"
    read -p "Overwrite? (y/N): " overwrite
    if [[ ! $overwrite =~ ^[Yy]$ ]]; then
        echo "Keeping existing .env. Run 'docker compose up -d' to start."
        exit 0
    fi
fi

# Collect information
echo -e "${BOLD}Let's set up your Control Tower.${NC}"
echo ""
echo "You'll need:"
echo "  1. An Anthropic API key"
echo "  2. A Discord server with a bot"
echo "  3. Channel IDs for your persona channels"
echo ""
echo -e "${YELLOW}Don't have a Discord bot yet?${NC}"
echo "  → https://discord.com/developers/applications"
echo "  → Create app → Bot → Reset Token → Copy it"
echo "  → Enable: Message Content Intent, Server Members Intent"
echo "  → OAuth2 → URL Generator → bot scope → Send Messages + Read History"
echo "  → Invite bot to your server"
echo ""

read -p "Ready to continue? (Y/n): " ready
if [[ $ready =~ ^[Nn]$ ]]; then
    echo "No problem. Run this script again when you're ready."
    exit 0
fi

echo ""
echo -e "${BOLD}Step 1: API Key${NC}"
echo -e "${CYAN}Get yours at: https://console.anthropic.com${NC}"
read -sp "Anthropic API Key: " ANTHROPIC_API_KEY
echo ""

if [[ ! $ANTHROPIC_API_KEY =~ ^sk-ant- ]]; then
    echo -e "${YELLOW}Warning: Key doesn't start with 'sk-ant-' — are you sure it's correct?${NC}"
fi

echo ""
echo -e "${BOLD}Step 2: Discord Bot${NC}"
read -sp "Discord Bot Token: " DISCORD_BOT_TOKEN
echo ""

echo ""
echo -e "${BOLD}Step 3: Discord Server${NC}"
echo -e "${CYAN}(Enable Developer Mode: Settings → Advanced → Developer Mode)${NC}"
read -p "Discord Server (Guild) ID: " DISCORD_GUILD_ID

echo ""
echo -e "${BOLD}Step 4: Channel IDs${NC}"
echo -e "${CYAN}Right-click each channel → Copy Channel ID${NC}"
echo ""
read -p "#engineering (Ada - CTO): " ENGINEERING_CHANNEL_ID
read -p "#product (Grace - CPO): " PRODUCT_CHANNEL_ID
read -p "#marketing (Tony - CMO): " MARKETING_CHANNEL_ID
read -p "#finance (Val - CFO): " FINANCE_CHANNEL_ID

echo ""
echo -e "${BOLD}Step 5: Company Info${NC}"
read -p "Company name [My Startup]: " COMPANY_NAME
COMPANY_NAME=${COMPANY_NAME:-My Startup}

# Write .env file
cat > .env << EOF
# Control Tower Configuration
# Generated by setup wizard on $(date -u +"%Y-%m-%d %H:%M UTC")

# API Keys
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}

# Discord
DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
ENGINEERING_CHANNEL_ID=${ENGINEERING_CHANNEL_ID}
PRODUCT_CHANNEL_ID=${PRODUCT_CHANNEL_ID}
MARKETING_CHANNEL_ID=${MARKETING_CHANNEL_ID}
FINANCE_CHANNEL_ID=${FINANCE_CHANNEL_ID}

# Settings
COMPANY_NAME=${COMPANY_NAME}
EOF

echo ""
echo -e "${GREEN}✓ Configuration saved to .env${NC}"
echo ""

# Add .env to .gitignore if not already there
if [ -f .gitignore ]; then
    if ! grep -q "^\.env$" .gitignore; then
        echo ".env" >> .gitignore
        echo -e "${GREEN}✓ Added .env to .gitignore${NC}"
    fi
else
    echo ".env" > .gitignore
    echo -e "${GREEN}✓ Created .gitignore with .env${NC}"
fi

echo ""
echo -e "${BOLD}Ready to launch!${NC}"
echo ""
read -p "Start Control Tower now? (Y/n): " start_now

if [[ ! $start_now =~ ^[Nn]$ ]]; then
    echo ""
    echo -e "${BLUE}Building and starting Control Tower...${NC}"
    echo ""
    
    if docker compose up -d --build; then
        echo ""
        echo -e "${GREEN}╔═══════════════════════════════════════════════════════════╗${NC}"
        echo -e "${GREEN}║${NC}  ${BOLD}🎉 Control Tower is running!${NC}                            ${GREEN}║${NC}"
        echo -e "${GREEN}╚═══════════════════════════════════════════════════════════╝${NC}"
        echo ""
        echo "Your AI executive team is ready:"
        echo ""
        echo "  Ada ✦ (CTO)  → #engineering"
        echo "  Grace 🚀 (CPO) → #product"
        echo "  Tony 🔥 (CMO)  → #marketing"
        echo "  Val 💰 (CFO)   → #finance"
        echo ""
        echo "Try posting in #engineering:"
        echo "  \"Hi Ada, what's your role on this team?\""
        echo ""
        echo -e "${CYAN}Commands:${NC}"
        echo "  View logs:    docker compose logs -f"
        echo "  Stop:         docker compose down"
        echo "  Restart:      docker compose restart"
        echo ""
    else
        echo ""
        echo -e "${RED}Failed to start. Check the error above.${NC}"
        echo "You can try manually: docker compose up --build"
        exit 1
    fi
else
    echo ""
    echo "Configuration saved. When ready, run:"
    echo "  docker compose up -d --build"
    echo ""
fi
